---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-vote-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: azure-vote-prod
  chart:
    git: git@github.com:vyta/arc-helm-demo.git
    path: charts/azure-vote
    ref: master
  values:
    image:
      repository: dstrebel/azurevote
      tag: v1
    replicaCount: 1
